### ISSUE TITLE
Go Language family CNB releases should contain a buildpackage artifact

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/go#1]
**Context**
As buildpackages start to become the standard of shipping our CNBs, we should build a buildpackage of our Paketo language family Go CNB. This will make it way easier for users to consume specific language family buildpacks.

**Proposal**
start publishing a Paketo Go buildpackage whenever we ship a new release artifact. 

**Notes/Helpful Links**
- The pack command that we will have to run to do this is `pack package-buildpack <NAME-OF-ARTIFACT> --package-config <Path/To/Package.toml>`. 

**Acceptance/Deliverables**
- Go Language Family CNB github releases should contain an online buildpackage artifact in the release assets.
- Go Buildpackage can be downloaded from Github and used to `pack build` apps

**Comment by ryanmoran** [comment]
The latest releases include a buildpackage: https://github.com/paketo-buildpacks/go/releases/tag/v0.0.3.

**Comment by kvedurmu** [comment]
Looks great! Downloaded the latest buildpackage and I was able to `pack build` a Go app using it. Closing this.
