### ISSUE TITLE
Go Paketo Language Family Buildpacks should receive implementation buildpack updates

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/go#3]
**Context**
We should set up our pipelines to start updating the language family CNB level buildpack.toml anytime there is a new version of one of its Implementation Paketo Buildpacks.

**Proposal**
Attempt to use Github Actions to start auto-PRing implementation CNB versions in the Paketo Go Language family buildpacks. If pipelines pass, the update PR should be automatically merged.

**Acceptance Criteria**
GIVEN any implementation CNB in a language family CNB(Go) is updated
THEN I see that there is a PR to the language family CNB with the implementation CNB updates
AND when the pipelines pass
THEN I see that the PR has been auto-merged

**Notes**
Here is a concourse task that is used bump cnb dependencies:
https://github.com/cloudfoundry/buildpacks-ci/tree/ce29842908d77018051422560db38df9fdbfa33c/tasks/cnb/update-cnb-dependency

**Comment by ryanmoran** [comment]
This is now happening when new implementation buildpacks are released: https://github.com/paketo-buildpacks/go/pull/33.

**Comment by kvedurmu** [comment]
Looks great! The latest Go Paketo Buildpack release (https://github.com/paketo-buildpacks/go/releases/tag/v0.0.4) has the latest versions of each Go Implementation CNB. Closing this.
