### ISSUE TITLE
Run go generate before building

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/go#337]
## What happened?

When building our go app images with dockerfiles, we normally run `go generate ./...` before installing/building our application in order to run a tool that embeds files. 

Would it be possible to create a go-generate buildpack that could be included in custom builders that would be run before the `go-build` buildpack in order to do things like embed files. In Go 1.16, there will be native file embedding support so this will likely not be necessary after then.

## Build Configuration

Please provide some details about your build configuration.

Using pack `v0.13.1` and the go-buildpack `v0.2.4`

## Checklist

Please confirm the following:

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
In thinking about how we would integrate this into the existing buildpack ordering, I have a couple of questions:

1. How would this buildpack detect? This matters because we'd likely not want to always run `go generate`, esp. if its a really slow process.

2. How do the tools referenced by the `//go:generate <some-tool>` directives end up in the build container?

**Comment by genevieve** [comment]
> 1. How would this buildpack detect? This matters because we'd likely not want to always run go generate, esp. if its a really slow process.

Could we introduce a special build-time env var like `BP_GO_GENERATE` that when enabled causes this buildpack to pass detection? In our case, since we have our own builder, we would probably just inject this buildpack in the `order.group` between the other go buildpacks and have it always pass detection. In order to have this buildpack be part of the paketo community, I think an env var or some other flag would be appropriate.

> 2. How do the tools referenced by the //go:generate <some-tool> directives end up in the build container?

If the buildpack requires a user to enable the flag described above, they would also be responsible for ensuring that the stack they are using supports those CLIs needed for generating. In our case, since we have our own stack, we can add the tools we need as required.

**Comment by stefanlesperance** [comment]
In case it's of interest, @genevieve and I created the buildpack: https://github.com/stefanlesperance/go-generate

**Comment by fg-j** [comment]
hey @stefanlesperance or @genevieve -- what does your order group look like including the `go-generate` buildpack, and why did you choose the order you did? I'm investigating creating an alternate Go Generate buildpack at the moment.

**Comment by genevieve** [comment]
Hey Frankie! This is the order that worked for us:

```
[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.6"
  [[order.group]]
    id = "paketo-buildpacks/go-generate"
    version = "0.0.1"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.1.2"
```

**Comment by fg-j** [comment]
Thanks. Looks like you're vendoring dependencies before build. Is that right?

**Comment by genevieve** [comment]
Yes, you are correct

**Comment by fg-j** [comment]
@genevieve  In case you're interested, I've just opened an RFC talking about what a Paketo `go generate` buildpack might do: https://github.com/paketo-buildpacks/go/pull/367

**Comment by fg-j** [comment]
Discussion on the [RFC](https://github.com/paketo-buildpacks/go/pull/367) has revealed some thorny technical details about implementing detection logic for the buildpack that's more complex than checking an environment variable. But it's not clear whether a better `[[ requires ]]` API would be necessary for users to get value from a Go Generate Buildpack. 

So for that reason, [we want to put a Go Generate buildpack in the “sandbox” of the paketo-community org](https://github.com/paketo-buildpacks/go/pull/367#issuecomment-771886349). That way, folks can incorporate it into their builds and provide feedback about their use-cases. We can experiment with the buildpack's API before (potentially) promoting it into the Paketo Go language family buildpack.

@stefanlesperance @genevieve would you be interested in having your implementation officially adopted into the paketo-community org? (Here's [more info on what that entails](https://github.com/paketo-buildpacks/rfcs/blob/main/implemented/0008-paketo-community.md).)

**Comment by genevieve** [comment]
Hey @fg-j! Yeah, that makes sense. Let us know what are the next steps.

**Comment by fg-j** [comment]
Next steps:
- Per the [Paketo Community RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/implemented/0008-paketo-community.md): "the maintainers of the project may open a proposal for their project to be added to the Paketo Community organization."
    - You can open an issue against the [paketo-buildpacks/rfcs](https://github.com/paketo-buildpacks/rfcs) repo proposing adding the go generate buildpack to Paketo Community
- Once you get approvals from at least 2 Paketo maintainers (I'm one!), you'll need to transfer ownership of the repo to @ryanmoran, who can then move it into Paketo Community
- Then, I'll open another PR adding the environment variable configuration options that I outlined in the [RFC](https://github.com/paketo-buildpacks/go/pull/367).

**Comment by genevieve** [comment]
Added an rfc for the buildpack! Thanks @fg-j !

**Comment by genevieve** [comment]
I'm going to close this issue since the go-generate buildpack is available in the community org and can be enabled in custom builders.
