### ISSUE TITLE
Self-nomination as Go contributor

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/go#338]
In keeping with [the Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the Go language family.

I have recently contributed by opening issues addressing [a layer reuse issue related to go build targets](https://github.com/paketo-buildpacks/go-build/issues/88) and another related to the [buildpack respecting GOFLAGS](https://github.com/paketo-buildpacks/go-build/issues/89). I have also submitted a PR [simplifying go build flags](https://github.com/paketo-buildpacks/go-build/pull/78).

**Comment by ryanmoran** [comment]
This has been open far too long. @ForestEckhardt can we get a vote from you?

**Comment by ForestEckhardt** [comment]
Congrats @fg-j. I will add you to the contribution group in short order!
