### ISSUE TITLE
Go Buildpack should support apps using glide

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/go#4]
We should look into adding support for apps using glide.

**Comment by kvedurmu** [comment]
@ryanmoran any thoughts on this one? It was a rather old issue and I wonder if it's even worth supporting since Glide isn't really supported anymore.

**Comment by ryanmoran** [comment]
@kvedurmu could we get away with removing this since we'd be making this a new major version release? I took a look at the Glide repo (hasn't been updated in about 1 year) and there is this statement on the README:
> The Go community is now using Go Modules to handle dependencies. Please consider using that instead of Glide. Glide is now mostly unmaintained.

**Comment by kvedurmu** [comment]
Yeah that makes sense. Closing this.
