### ISSUE TITLE
Nominating @fg-j as a Go subteam maintainer

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/go#400]
@fg-j has made many contributions to Go buildpacks. Their most significant contribution was lobbying for the introduction of the `go-generate` buildpack:
* Issue #337 
* PR #367

They also wrote the implementation to expand the functionality of the [`go-generate` buildpack](https://github.com/paketo-community/go-generate/pull/9).

@ryanmoran looking for your review and approval.

**Comment by ryanmoran** [comment]
With 2/2 affirmative votes from maintainers, welcome @fg-j to the Go Maintainers subteam!
