### ISSUE TITLE
Release Paketo Go buildpack

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/go#427]
Release in the week of May 17th if relevant changes or dependency updates are merged.

What steps did you take to close this issue? What resources did you use? How long did you spend on this task this week? **Answer in a comment.**

**Comment by fg-j** [comment]
Released [v0.7.0](https://github.com/paketo-buildpacks/go/releases/tag/v0.7.0)

**Comment by thitch97** [comment]
In an effort to de-clutter the project board, we are moving away from recurring issues such as this one. This task will instead  be added to a checklist of tasks to be completed on a weekly basis.
