### ISSUE TITLE
Add git buildpack into the all order groups

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/go#557]
## What happened?

We want to add the `git` buildpack into all order groups. This adds two use-cases:
- add git revision metadata to the built image
- clone private repositories

See [git buildpack](https://github.com/paketo-buildpacks/git) for more detail.

Resolves paketo-buildpacks/go-mod-vendor#140.

## Acceptance Criteria
- [ ] Automated acceptance test that verifies that the `git` buildpack is participating in at least one build
- [ ] `git` buildpack has been added in the `buildpack.toml` (prior to `go-mod-vendor`) and `package.toml` for all order groups
  - should be marked `optional=true` since it is not required for any existing workflows / order groups to succeed. Git is not a requirement for golang!

### Notes
- `jam` will automatically keep the versions of the `git` buildpack updated in `buildpack.toml`.

**Comment by ryanmoran** [comment]
The `git` buildpack provides functionality beyond simply allowing private repositories to be cloned. I would expect that we should include it in all order groupings. It would allow folks to do things like embed the revision of their code into the binary they are building during the execution of the `go-build` buildpack.

**Comment by joshuatcasey** [comment]
@ryanmoran thanks for the catch, we've updated the issue/PR to reflect that the `git` buildpack will be included in all order groups as an optional buildpack.

**Comment by fg-j** [comment]
Blocked by https://github.com/buildpacks/pack/issues/1379 -- git buildpack cannot currently be packaged with other buildpacks in this language family
