### ISSUE TITLE
Go Paketo Buildpack should support layer caching

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/go#6]
This might already be supported, but it would be great if the Go Paketo Buildpack supports layer caching.

**Comment by ryanmoran** [comment]
I believe this is already working. Can you provide some details about where or how it is missing?

**Comment by kvedurmu** [comment]
Just confirmed that this is working. This issue was pulled over as part of the initial migration of issues after the Paketo launch. Closing this.
